--- Makefile   2021-03-12 04:48:21.268725458 +0100
+++ Makefile	2021-03-12 04:49:09.332724040 +0100
@@ -21,7 +21,7 @@
 #
 RMTOO_CALL ?= rmtoo
 RMTOO_CONFIG=Config.json
-RMTOO_CONTRIB_DIR ?= /usr/local/pkg/rmtoo/rmtoo
+RMTOO_CONTRIB_DIR ?= /usr/local/rmtoo
 
 CALL_RMTOO=${RMTOO_CALL} -j file://${RMTOO_CONFIG}
 
